# Generated by Django 3.0.6 on 2020-06-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallpaperapi', '0002_imagewalls'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewalls',
            name='image_cateogry',
            field=models.CharField(choices=[('None', 'None'), ('Anime', 'Anime'), ('Nature', 'Nature'), ('GOD', 'GOD'), ('Gaming', 'Gaming')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='imagewalls',
            name='image_id',
            field=models.TextField(default='8e5384392b0a4cd3a3622b6219587c4b', unique=True),
        ),
    ]
