# Generated by Django 3.0.6 on 2020-06-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallpaperapi', '0003_auto_20200618_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewalls',
            name='image_id',
            field=models.TextField(default='766956dbb1aa49bf879d56147d04c8bc', unique=True),
        ),
    ]
