# Generated by Django 3.0.6 on 2020-06-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallpaperapi', '0005_auto_20200619_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewalls',
            name='image_id',
            field=models.TextField(default='713b56bc12fd46dfb07e2377b6c7142a', editable=False),
        ),
    ]
