# Generated by Django 3.0.6 on 2020-06-25 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Wallpaperapi', '0006_auto_20200619_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewalls',
            name='image_id',
            field=models.TextField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='imagewalls',
            name='user_foreign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
