# Generated by Django 3.0.6 on 2020-06-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallpaperapi', '0007_auto_20200625_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewalls',
            name='image_id',
            field=models.TextField(editable=False, unique=True),
        ),
    ]
