# Generated by Django 3.0.6 on 2020-06-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallpaperapi', '0008_auto_20200625_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='BackGroundTheme',
            field=models.ImageField(default=1, upload_to='Themes'),
            preserve_default=False,
        ),
    ]
