# Generated by Django 3.0.8 on 2020-07-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallpaperapi', '0011_imagewalls_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='liked_images',
            field=models.ManyToManyField(blank=True, to='Wallpaperapi.ImageWalls'),
        ),
    ]
